[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.8.22"

[[dependencies]]
  name = "github.com/cenkalti/backoff"
  version = "1.0.0"

[[dependencies]]
  name = "github.com/google/gops"
  version = "0.3.1"

[[dependencies]]
  branch = "master"
  name = "github.com/termie/go-shutil"
