[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = ">=1.8.0, <2.0.0"

[[dependencies]]
  name = "github.com/cenkalti/backoff"
  version = "1.0.0"

[[dependencies]]
  name = "github.com/google/gops"
  version = "0.3.1"

[[dependencies]]
  branch = "master"
  name = "github.com/termie/go-shutil"

[[dependencies]]
  name = "github.com/posener/complete"
  revision = "55ecf96557cf9eb690221d52354c4408ff59003a"
