[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = ">=1.8.0, <2.0.0"

[[constraint]]
  name = "github.com/cenkalti/backoff"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/gops"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/termie/go-shutil"

[[constraint]]
  name = "github.com/posener/complete"
  version = "1.1"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
